### ISSUE TITLE
iOS Install Guide | React Native 60.5

### ISSUE THREAD

**Issue by jordangrant** [davidohayon669/react-native-youtube#401]
This is the only procedure that worked for me when installing this library. It solves: 
- Invariant Violation: requireNativeComponent:"ReactYoutube" was not found in UIManager
- Blank white thumbnail, video wont play
- Archiving build error
- Random build errors on iOS

**If the readme isn't working for you, give this a try...**

### Procedure
1. `npm install react-native-youtube --save`
2. In Xcode, add _RCTYouTube.xcodeproj_ to Libraries
3. Build Phases > Link Binary With Libraries > add _libRCTYouTube.a_
4. Click on the RCTYouTube Library, mark the Pods header search path as recursive
<img width="1501" alt="Screen Shot 2019-10-06 at 4 22 31 PM" src="https://user-images.githubusercontent.com/7986493/66275342-9cada280-e855-11e9-86f7-60a93416a67a.png">

5. Open your Podfile, add `pod "YoutubePlayer-in-WKWebView", "~> 0.3.3" `or whatever the latest version is of https://github.com/hmhv/YoutubePlayer-in-WKWebView then run:
```
cd ios
pod update
``` 
7. After running `pod update`, make sure in Xcode, Pods > Pods folder > _YoutubePlayer-in-WKWebView_ is there and in Products _libYoutubePlayer-in-WKWebView.a_ is there also.
<img width="341" alt="Screen Shot 2019-10-05 at 7 28 23 PM" src="https://user-images.githubusercontent.com/7986493/66262074-79c4b500-e7a7-11e9-943f-e9006dfd9e43.png">

- 7.1 **If it doesn’t show in Xcode after pod update** close Xcode, delete the Pods folder and podfile.lock and do pod update again.

Now click Run in Xcode.
It’ll use the manually linked RCTYouTube library coupled with the WKWebView dependency as a pod.

Time to solve: 2 days

**Comment by tkulpa** [comment]
Tried it but, cannot make libYoutubePlayer-in-WKWebView.a appear inside Products folder

**Comment by nic-thomson** [comment]
@jordangrant  Thanks for taking the time to put this together your description worked perfectly for me.  I owe you a beer!

**Comment by LAITONEN** [comment]
@davidohayon669 not everyone is using RN 0.60<

**Comment by rstcom919** [comment]
Hi, @jordangrant
thanks for your info, but not working well...

**Comment by neilgamb** [comment]
Thank you! this worked for me on a `"react-native": "^0.57.0",` app
