### ISSUE TITLE
Problem using two component instances on Android

### ISSUE THREAD

**Issue by stefanosandes** [davidohayon669/react-native-youtube#420]
On android, if I put two `Youtube` components together and try to play one while another ois paused, they dont work and in some seconds the app crashes.

**Comment by davidohayon669** [comment]
[this is un-adressable right now.](https://github.com/inProgress-team/react-native-youtube#multiple-youtube--instances-on-android). I might add a wrapping around [this library](https://github.com/PierfrancescoSoffritti/Android-YouTube-Player) in the future

**Comment by LonelyCpp** [comment]
I had similar constraints of having multiple youtube players in one screen. The only way to go about this seems to be to use webviews in app. The library mentioned above also seems to use the web player.

I've written a simple wrapper around the webplayer with react-native-webview. You can check it out https://github.com/LonelyCpp/react-native-youtube-iframe :)
