### ISSUE TITLE
AutoPlay in list view

### ISSUE THREAD

**Issue by tapannathvani** [davidohayon669/react-native-youtube#424]
Hello, I want to do AutoPlay in Flatlist but every videos are playing and I need to play only 1 video and the previous one should be auto paused. What will be the best behaviour to achieve this. The same as in Facebook

Here is the configuration of my YouTube component

       <YouTube
                                                videoId="nQ7mhC5_Rys" // The YouTube video ID
                                                play={false} // control playback of video with true/false
                                                fullscreen={false} // control whether the video should play in fullscreen or inline
                                                loop = {false} // control whether the video should loop when ended
                                                showFullscreenButton = {false}
                                                showinfo = {false}
                                                controls = {0}
                                                rel = {false}
                                                onReady={e => this.setState({ isReady: true })}
                                                onChangeState={e => this.setState({ status: e.state })}
                                                onChangeQuality={e => this.setState({ quality: e.quality })}
                                                onError={e => this.setState({ error: e.error })}
                                                style={{ alignSelf: 'stretch',width: '100%',
                                                     }}
                                            />

**Comment by davidohayon669** [comment]
@tapannathvani You need to somehow control the different players state in you App code
