### ISSUE TITLE
Invariant Violation: requireNativeComponent:"ReactYoutube" was not found in UIManager.

### ISSUE THREAD

**Issue by fibushj** [davidohayon669/react-native-youtube#425]
Hello,
This issue was raised in the past by other users, but the solutions suggested there didn't help me.
I get this error message when I use the component. 
![image](https://user-images.githubusercontent.com/46170238/71534063-d0eca880-2904-11ea-8c9a-66355cbe784e.png)

**Comment by fibushj** [comment]
I'll add that in VSCode, hovering over those 3 dots:
![image](https://user-images.githubusercontent.com/46170238/71534146-553f2b80-2905-11ea-8d40-446369268457.png)

gives the message: 
Could not find a declaration file for module 'react-native-youtube'. '...node_modules/react-native-youtube/main.js' implicitly has an 'any' type.
  Try `npm install @types/react-native-youtube` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-youtube';`ts(7016)

**Comment by graphan** [comment]
@fibushj You need to link a library to the app.
In here you can find more information: https://github.com/facebook/react-native/issues/27740

**Comment by davidohayon669** [comment]
@firodj got to follow installation steps
