### ISSUE TITLE
Invariant Violation: requireNativeComponent:"ReactYoutube" was not found in UIManager 

### ISSUE THREAD

**Issue by shobujroy** [davidohayon669/react-native-youtube#430]
Hi there,

I'm a beginner in react native. I have been trying to play youtube videos in android. But I found this error **_"ReactYoutube" was not found in UIManager "_**. I can see someone maybe fixed the issue for IOS which I haven't tried though.

It will be really appreciated if someone can help me to fix it.

Thank you,

**Comment by TheMainCoder** [comment]
Same here, for me the error occurs using the start example provided

**Comment by gauravsbagul** [comment]
Same issue here
	`"react": "16.8.6",
	"react-native-youtube": "^2.0.0",
        "react-native": "0.60.4",`

**Comment by gauravsbagul** [comment]
Solved this issue by adding libraries in 
![Screenshot 2020-02-29 at 4 51 39 PM](https://user-images.githubusercontent.com/25247251/75606792-79420780-5b16-11ea-8a79-a2ede20ac31d.png)

add this and pod install and done!

**Comment by davidohayon669** [comment]
@shobujroy can you provide the process of installing that didn't ended working?
