### ISSUE TITLE
Why is Api key needed for Android?

### ISSUE THREAD

**Issue by PierreCapo** [davidohayon669/react-native-youtube#431]
According to the doc, it seems that an api key provided by Youtube is mandatory. However, using the react-native-youtube component without the API key is working well. Furthermore, when reading [this page from Google help center](https://support.google.com/code/answer/74718?hl=en), it seems that an API key is only needed for write or upload operations, not for read operations. Could you confirm/invalidate the need of the Youtube API key? And if it's needed, why is the example app working without a valid api key on Android?
Thanks in advance.

**Comment by shani-maini** [comment]
same here why need an API key?

**Comment by davidohayon669** [comment]
@PierreCapo I guess there is no problem of it's working without one.. if it was important, YouTube would have block that
