### ISSUE TITLE
App crashes when return from another tab in a tab navigator

### ISSUE THREAD

**Issue by mauriciosoares01** [davidohayon669/react-native-youtube#434]
The app has the following navigation structure:

> Home
>> VideoPlayer

>Playlists

>Configs

In home there is a video's list, so the video player screen is called when an video e touched in the home screen. If the user switch for another tab and back to the home tab (where the VideoPlayer is loaded) the app crashes.

Environment:
Platform: Android (wasn't tested in iOS)
react-native-youtube: ^2.0.0
@react-navigation/bottom-tabs: ^5.0.5
react-native: 0.61.5

**Comment by davidohayon669** [comment]
Android ? iOS?

**Comment by mauriciosoares01** [comment]
Android.

**Comment by mauriciosoares01** [comment]
I'm using a workaround with a fullscreen modal. Works pretty well, but the issue persists.

**Comment by extracold1209** [comment]
I had same issue and I resolved below way

```typescript
import { useIsFocuesed } from '@react-navigation/native'

const Layout: React.FC = () => {
    const isFocuesed = useIsFocuesed();

    return (
        // ...
        {isFocused && <YouTube ... />}
        // ...
    }
}
```
