### ISSUE TITLE
Duplicate videos on the React Native list

### ISSUE THREAD

**Issue by blitsoftwares** [davidohayon669/react-native-youtube#440]
Hello people

I have a list of videos that comes from the API, the IDs are different, but the players appear the same video.

![WhatsApp Image 2020-04-15 at 23 12 00](https://user-images.githubusercontent.com/26930300/79410531-b2232800-7f6e-11ea-87da-3dd82ffa7547.jpeg)

List 

![Captura de Tela 2020-04-15 às 23 15 45](https://user-images.githubusercontent.com/26930300/79410654-0a5a2a00-7f6f-11ea-84f9-7deba1e212af.png)

card YouTube

![Captura de Tela 2020-04-15 às 23 14 01](https://user-images.githubusercontent.com/26930300/79410570-ccf59c80-7f6e-11ea-9828-dde43eed16a4.png)

I didn't find the reason :-(

**Comment by blitsoftwares** [comment]
**Multiple <YouTube /> instances on Android**

The YouTube API for Android is a singleton. What it means is that unlike the iOS implementation, no two players can be mounted and play a video at the same time. If you have two scenes that happen to live together, or come one after the other (such as when navigating to a new scene), The new <YouTube /> Will take the focus of the singleton and play the video, but after being unmounted, the older mounted <YouTube /> will not be able to take the role back, and will need to be re-mounted.

:-(

**Comment by dev-reactjs** [comment]
Any solution for this?
