### ISSUE TITLE
Is it legal to show music video from youtube with this depedency?

### ISSUE THREAD

**Issue by YudeMgoy** [davidohayon669/react-native-youtube#454]

**Comment by webdevbyjoss** [comment]
This extension is a wrapper for the following two APIs:

- On Android: YouTube Android Player API which is officially provided by Google (Youtube owners) https://developers.google.com/youtube/android/player/

- On iOS: Youtube Player KWWebView https://github.com/hmhv/YoutubePlayer-in-WKWebView that uses an HTML5 version of the player

As long as those two are legal, using this extension should be legitimate as well.
