### ISSUE TITLE
Can't start react-native-youtube on Ubuntu/Android

### ISSUE THREAD

**Issue by mlapis** [davidohayon669/react-native-youtube#459]
Hi,
I am trying to make react-native-youtube run locally on my Ubuntu 18.04 + Android. I installed it with following command in my react native app:

`npm install react-native-youtube -S`

Unfortunately I get following error message when starting the app.

`Invariant Violation: Invariant Violation: requireNativeComponent: "ReactYouTube" was not found in the UIManager.
`
I am not quite sure what is the reason for this and have a hard time debugging it, as I am quite new to react native. Any help how to debug it better is also greatly appreciated. I am not quite sure to be honest if this is an issue with react-native-youtube or something on my side.

**Comment by davidohayon669** [comment]
@mlapis seems like a problem with connecting the library. try removing node_modules and install everything again

**Comment by mlapis** [comment]
@davidohayon669 thank you for the very fast answer! I just tried it with 
```
$ rm -R node_modules/
$ npm install
```
Unfortunately the result is pretty much the same. I have to add that I am using expo. Is there a chance this might cause any issues like that?

**Comment by davidohayon669** [comment]
@mlapis AFAIK expo does not support linking native libraries

**Comment by mlapis** [comment]
I will check it out without expo. Thank you!
