### ISSUE TITLE
LIBRARY NO LONGER MAINTAINED ?

### ISSUE THREAD

**Issue by zabojad** [davidohayon669/react-native-youtube#553]
It seems that this lib is not maintained anymore by its owners... Is there already a fork which is continuing the work on this lib or should we create one?

**Comment by davidohayon669** [comment]
@zabojad do you want merge permissions?

**Comment by zabojad** [comment]
@davidohayon669 which PR is it?

**Comment by zabojad** [comment]
@davidohayon669 Fine for me, I'll do my best to help here!

**Comment by davidohayon669** [comment]
@zabojad got it... let's merge some things and test them and publish when done
